### ISSUE TITLE
migrate to paypal user?

### ISSUE THREAD

**Issue by grawk** [paypal/nemo-page#1]
I'd like to promote this on the nemo home page, nemo-docs repo, nemo twitter account, vimeo tutorial, etc. But first it needs to be more formally released. I.e. needs an appropriate LICENSE.md file, needs to be migrated to the paypal github account. Would that be ok with you?

**Comment by OuranosSkia** [comment]
Totally missed this. I would be very ok with that.

**Comment by OuranosSkia** [comment]
That was actually my intention in the first place.

**Comment by grawk** [comment]
Cool. Are you a member of the paypal org? If not you should request membership from Duane O'Brien in the #opensource slack channel

**Comment by OuranosSkia** [comment]
I am. Would you like me to initiate the transfer to the org?

**Comment by OuranosSkia** [comment]
Completed

**Comment by grawk** [comment]
:dancer:
